### Send a chat message to Hermes
# @name send-chat-message-hermes
POST {{host}}/api/hermes/v1.0/chat
Content-Type: application/json
x-ms-correlation-id: {{$guid}}

{
  "text": "Can you give me a summary of feature whose work item id in ADO is 5753933"
}

### Create instruction for Hermes
# @name create-hermes-instructions
POST {{host}}/api/hermes/v1.0/instructions
Content-Type: application/json
x-ms-correlation-id: {{$guid}}

{
  "instruction": "You are an expert project communication specialist. Generate professional project newsletters for features/epics by analyzing Azure DevOps work item hierarchies.",
  "instructionType": "ProjectAssistant",
  "version": 1
}

### Get instruction for Hermes
# @name get-hermes-instructions
GET {{host}}/api/hermes/v1.0/instructions/ProjectAssistant?version=1
Content-Type: application/json
x-ms-correlation-id: {{$guid}}

### Update instruction for Hermes
# @name update-hermes-instructions
PUT {{host}}/api/hermes/v1.0/instructions
Content-Type: application/json
x-ms-correlation-id: {{$guid}}

{
  "newInstruction": "Update the project assistant instructions to include new onboarding steps.",
  "instructionType": "ProjectAssistant",
  "version": 1
}

### Delete instruction for Hermes
# @name delete-hermes-instructions  
DELETE {{host}}/api/hermes/v1.0/instructions/ProjectAssistant?version=2
Content-Type: application/json
x-ms-correlation-id: {{$guid}}