### Create sample data in Hermes.
# @name create-sample-data-hermes
POST {{host}}/api/storage
Content-Type: application/json
x-ms-correlation-id: {{$guid}}

{
  "id": "sample-id-123",
  "partitionkey": "sample-partition",
  "data": "Sample data value"
}